#===================================================================================DATA PROCESSING PARAMETERS===================================================================================
sample_size: 10 # number of rows to sample

#===================================================================================MODEL TRAINING PARAMETERS===================================================================================
data_split:
  test_size: 0.1
  random_state: 42
  target_column: num

data_transform:
  categorical_cols:
    - sex
    - cp
    - fbs
    - restecg
    - exang
    - slope
    - thal
  numerical_cols:
    - age
    - trestbps
    - chol
    - oldpeak
    - ca
    - thalch
  impute_strategy_num: knn # Options: mean, median, knn

modeling:
  model_type: random_forest # Options: random_forest, logistic_regression, k_neighbors 
  random_state: 42
  num_iter: 100
  num_folds: 5
  scoring: accuracy
