#===================================================================================DATA PROCESSING PARAMETERS===================================================================================
sample_size: 10 # number of rows to sample

#===================================================================================MODEL TRAINING PARAMETERS===================================================================================
data_split:
  test_size: 0.1
  random_state: 42
  target_column: num